# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f140d9df7a96396bcb5843d445be980eb49fdd1f1b52d53ce189d848bbaab5b53450eb58a0b5727c4532d87a3a25e03a6a7b0efd3286d29b632b447d41b31dc

test:
  secret_key_base: e41deb199c154c62185019a56985219807a3b2c8467f1c1b88c8831f6f13f44935af3e3aa6bd67cbb4387c00bcec220fc02d7280c2f5579a05ae3162e888c9fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
